### ISSUE TITLE
Inference outputs are black images

### ISSUE THREAD

**Issue by kshitijqwerty** [nv-tlabs/STEAL#4]
I am running inference models, and the outputs are blank images.

**Comment by davidjesusacu** [comment]
Inference produces a set of output folders `output/class_1` `output/class_2` ... `output/class_20` (i.e for SBD)
Inside you will have the prediction of each image for each class id(folder name),  if there is no such class in the given image the prediction will be black (0). Otherwise, you will have a value from 0..255. 
If you are sure there is such a class in the image and it is being properly predicted.. try a different image visualizer. 
You can also try the ipython notebook to check all is properly set-up (this uses matplotlib to visualize)
